2025-01-16 20:43:45,221 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\zamin\PycharmProjects\pythonProject1\12_module\tests_12_4.py", line 20, in test_run
    runner_2 = Runner(50)
               ^^^^^^^^^^
  File "C:\Users\zamin\PycharmProjects\pythonProject1\12_module\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2025-01-16 20:43:45,221 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\zamin\PycharmProjects\pythonProject1\12_module\tests_12_4.py", line 10, in test_walk
    runner_1 = Runner('Петя', -15)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zamin\PycharmProjects\pythonProject1\12_module\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -15
